import React, { useState } from 'react';
import { GitPullRequest, Printer, Download, Sparkles, Trophy, ChevronRight, CheckCircle2 } from 'lucide-react';
import { useToast } from '../../../context/ToastContext';
import jsPDF from 'jspdf';

export const FixturesTab = ({ matches, user }) => {
  const { addToast } = useToast();
  const [bracketMode, setBracketMode] = useState('automatic');

  const handleGenerateAutomatic = () => {
    addToast(`Automatic Knockout Fixtures bracket generated for ${user?.sportName}!`, 'success');
  };

  const handlePrintFixtures = () => {
    window.print();
  };

  const handleDownloadPDF = () => {
    try {
      const doc = new jsPDF();
      doc.setFontSize(18);
      doc.text(`SEMS 2026 - ${user?.sportName} Official Tournament Fixtures`, 14, 22);
      doc.setFontSize(10);
      doc.text(`Generated by: ${user?.coordinatorName} (${user?.sportName} Coordinator)`, 14, 30);
      doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 36);

      doc.setFontSize(12);
      doc.text('Matches & Bracket Overview:', 14, 48);

      let y = 58;
      matches.forEach((m, idx) => {
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
        doc.text(`${idx + 1}. [${m.round}] ${m.team1} vs ${m.team2} - Date: ${m.date} ${m.time} @ ${m.venue}`, 14, y);
        y += 10;
      });

      doc.save(`${user?.assignedSport}_official_fixtures.pdf`);
      addToast('Official Fixtures PDF downloaded successfully!', 'success');
    } catch (err) {
      addToast('Error generating PDF', 'error');
    }
  };

  return (
    <div className="space-y-6 animate-fade-in">
      
      {/* Top Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white dark:bg-slate-900 p-6 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-soft">
        <div>
          <h3 className="text-lg font-black text-slate-900 dark:text-white uppercase tracking-wider">
            {user?.sportName} Fixtures & Tournament Bracket
          </h3>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
            Automatic and manual fixture bracket generation, print, and official PDF downloads.
          </p>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          <button
            onClick={handleGenerateAutomatic}
            className="px-4 py-2.5 rounded-xl bg-orange-500 hover:bg-orange-600 text-white font-bold text-xs shadow-md transition flex items-center gap-1.5"
          >
            <Sparkles className="w-4 h-4" /> Auto Generate Bracket
          </button>
          <button
            onClick={handlePrintFixtures}
            className="px-3.5 py-2.5 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200 font-bold text-xs hover:bg-slate-200 transition flex items-center gap-1.5"
          >
            <Printer className="w-4 h-4" /> Print
          </button>
          <button
            onClick={handleDownloadPDF}
            className="px-3.5 py-2.5 rounded-xl bg-slate-900 text-white dark:bg-slate-100 dark:text-slate-900 font-bold text-xs hover:bg-slate-800 transition flex items-center gap-1.5"
          >
            <Download className="w-4 h-4" /> Download PDF
          </button>
        </div>
      </div>

      {/* Bracket Visualization */}
      <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-soft overflow-x-auto">
        <h4 className="text-sm font-black text-slate-900 dark:text-white uppercase tracking-wider mb-6 flex items-center gap-2">
          <GitPullRequest className="w-4 h-4 text-orange-500" /> Interactive Knockout Bracket Tree
        </h4>

        <div className="min-w-[800px] grid grid-cols-3 gap-8 items-center py-4">
          
          {/* Column 1: Quarter Finals */}
          <div className="space-y-6">
            <span className="text-xs font-black text-orange-500 uppercase tracking-widest block text-center pb-2 border-b border-slate-100 dark:border-slate-800">
              Quarter Finals
            </span>
            <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-2">
              <div className="flex justify-between text-xs font-bold text-slate-900 dark:text-white">
                <span>MPEC Tigers</span>
                <span className="text-orange-500 font-black">3</span>
              </div>
              <div className="flex justify-between text-xs font-bold text-slate-400">
                <span>MPDC Champions</span>
                <span>1</span>
              </div>
            </div>
            <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-2">
              <div className="flex justify-between text-xs font-bold text-slate-900 dark:text-white">
                <span>MIPS Warriors</span>
                <span className="text-orange-500 font-black">2</span>
              </div>
              <div className="flex justify-between text-xs font-bold text-slate-400">
                <span>MPCPS Knights</span>
                <span>0</span>
              </div>
            </div>
          </div>

          {/* Column 2: Semi Finals */}
          <div className="space-y-12">
            <span className="text-xs font-black text-amber-500 uppercase tracking-widest block text-center pb-2 border-b border-slate-100 dark:border-slate-800">
              Semi Finals
            </span>
            <div className="p-5 rounded-2xl bg-gradient-to-r from-orange-500/10 to-amber-500/10 border border-orange-500/30 space-y-3">
              <div className="flex justify-between text-xs font-black text-slate-900 dark:text-white">
                <span>MPEC Tigers</span>
                <span className="text-orange-500">LIVE</span>
              </div>
              <div className="flex justify-between text-xs font-black text-slate-900 dark:text-white">
                <span>MIPS Warriors</span>
                <span className="text-orange-500">LIVE</span>
              </div>
              <span className="text-[10px] text-slate-400 block text-center">Winner Advances to Championship</span>
            </div>
          </div>

          {/* Column 3: Final */}
          <div className="space-y-6">
            <span className="text-xs font-black text-yellow-500 uppercase tracking-widest block text-center pb-2 border-b border-slate-100 dark:border-slate-800">
              Championship Final
            </span>
            <div className="p-6 rounded-3xl bg-slate-950 text-white border border-yellow-500/40 text-center space-y-3 shadow-xl">
              <Trophy className="w-10 h-10 text-yellow-400 mx-auto animate-bounce" />
              <h5 className="text-sm font-black uppercase text-yellow-400">{user?.sportName} Gold Medal Match</h5>
              <p className="text-xs text-slate-300">Winner TBD vs Winner TBD</p>
              <span className="px-3 py-1 rounded-full bg-yellow-500/20 text-yellow-300 text-[10px] font-bold inline-block">
                Scheduled for Aug 05
              </span>
            </div>
          </div>

        </div>
      </div>

    </div>
  );
};
