import React from 'react';
import { BarChart3, Download, FileSpreadsheet, FileText, CheckCircle2, TrendingUp, Users, MapPin, Award } from 'lucide-react';
import { useToast } from '../../../context/ToastContext';
import jsPDF from 'jspdf';

export const ReportsTab = ({ user }) => {
  const { addToast } = useToast();

  const handleDownloadPDF = () => {
    const doc = new jsPDF();
    doc.setFontSize(18);
    doc.text(`SEMS 2026 - ${user?.sportName} Comprehensive Analytics Report`, 14, 22);
    doc.setFontSize(10);
    doc.text(`Generated by Coordinator: ${user?.coordinatorName}`, 14, 30);
    doc.text(`Report Date: ${new Date().toLocaleDateString()}`, 14, 36);

    doc.setFontSize(12);
    doc.text('Key Analytics Summary:', 14, 48);
    doc.text('- Total Matches: 12 (5 Completed, 1 Running, 6 Upcoming)', 14, 58);
    doc.text('- Total Registered Athletes: 54 Players across 12 Teams', 14, 66);
    doc.text('- Overall Attendance Rate: 94.5%', 14, 74);
    doc.text('- Top Performing College: MPEC Tigers (80% Win Rate)', 14, 82);
    doc.text('- Central Arena Main Ground Usage: 65%', 14, 90);

    doc.save(`${user?.assignedSport}_analytics_report.pdf`);
    addToast('PDF Report downloaded successfully!', 'success');
  };

  const handleDownloadExcel = () => {
    addToast(`Excel analytical spreadsheet downloaded for ${user?.sportName}!`, 'success');
  };

  return (
    <div className="space-y-6 animate-fade-in">
      
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white dark:bg-slate-900 p-6 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-soft">
        <div>
          <h3 className="text-lg font-black text-slate-900 dark:text-white uppercase tracking-wider flex items-center gap-2">
            <BarChart3 className="w-5 h-5 text-orange-500" /> {user?.sportName} Reports & Data Analytics
          </h3>
          <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
            Matches, participation, attendance %, winning percentage, college performance, player stats & venue usage.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={handleDownloadExcel}
            className="px-4 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs shadow-md transition flex items-center gap-1.5"
          >
            <FileSpreadsheet className="w-4 h-4" /> Download Excel
          </button>
          <button
            onClick={handleDownloadPDF}
            className="px-4 py-2.5 rounded-xl bg-slate-900 text-white dark:bg-slate-100 dark:text-slate-900 font-bold text-xs hover:bg-slate-800 transition flex items-center gap-1.5"
          >
            <FileText className="w-4 h-4" /> Download PDF
          </button>
        </div>
      </div>

      {/* Analytics Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
        <div className="p-5 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-soft space-y-2">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">Total Matches</span>
          <p className="text-3xl font-black text-slate-900 dark:text-white">12 Matches</p>
          <p className="text-xs text-emerald-500 font-bold">5 Completed • 1 Running</p>
        </div>

        <div className="p-5 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-soft space-y-2">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">Attendance Rate</span>
          <p className="text-3xl font-black text-slate-900 dark:text-white">94.5%</p>
          <p className="text-xs text-orange-500 font-bold">High Spectator Turnout</p>
        </div>

        <div className="p-5 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-soft space-y-2">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">Top Win Percentage</span>
          <p className="text-3xl font-black text-slate-900 dark:text-white">80.0%</p>
          <p className="text-xs text-indigo-500 font-bold">MPEC Tigers (4 Wins)</p>
        </div>

        <div className="p-5 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-soft space-y-2">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">Active Athletes</span>
          <p className="text-3xl font-black text-slate-900 dark:text-white">54 Players</p>
          <p className="text-xs text-blue-500 font-bold">Across 5 Colleges</p>
        </div>
      </div>

      {/* Breakdown Details */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* College Performance Breakdown */}
        <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-soft space-y-4">
          <h4 className="text-sm font-black text-slate-900 dark:text-white uppercase tracking-wider flex items-center gap-2">
            <Award className="w-4 h-4 text-orange-500" /> College Performance Summary
          </h4>
          <div className="space-y-3">
            {[
              { college: 'MPEC Tigers', played: 5, won: 4, lost: 1, winRate: '80%' },
              { college: 'MIPS Warriors', played: 5, won: 3, lost: 2, winRate: '60%' },
              { college: 'MPCPS Knights', played: 4, won: 2, lost: 2, winRate: '50%' },
              { college: 'MPCP Eagles', played: 4, won: 1, lost: 3, winRate: '25%' },
            ].map((item, idx) => (
              <div key={idx} className="p-3 rounded-2xl bg-slate-50 dark:bg-slate-800/60 flex items-center justify-between text-xs">
                <div>
                  <span className="font-bold text-slate-900 dark:text-white block">{item.college}</span>
                  <span className="text-[10px] text-slate-400">Played {item.played} | Won {item.won} | Lost {item.lost}</span>
                </div>
                <span className="font-black text-orange-500">{item.winRate} Win Rate</span>
              </div>
            ))}
          </div>
        </div>

        {/* Venue Usage Stats */}
        <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-soft space-y-4">
          <h4 className="text-sm font-black text-slate-900 dark:text-white uppercase tracking-wider flex items-center gap-2">
            <MapPin className="w-4 h-4 text-indigo-500" /> Venue Utilization Index
          </h4>
          <div className="space-y-3">
            {[
              { venue: 'Central Arena Main Ground', matches: 6, usage: '50%' },
              { venue: 'Indoor Sports Complex Hall A', matches: 4, usage: '33%' },
              { venue: 'Ground 2 Outdoor Stadium', matches: 2, usage: '17%' },
            ].map((v, idx) => (
              <div key={idx} className="p-3 rounded-2xl bg-slate-50 dark:bg-slate-800/60 flex items-center justify-between text-xs">
                <span className="font-bold text-slate-900 dark:text-white">{v.venue}</span>
                <span className="font-bold text-indigo-500">{v.matches} Matches ({v.usage})</span>
              </div>
            ))}
          </div>
        </div>
      </div>

    </div>
  );
};
